/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aspectj.logging.example;

import com.example.SampleService;

public class App {

    public static void main(String[] args) {
        SampleService service = new SampleService();
        service.performTask();
        service.anotherTask();
    }
}
